# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jon White's Photo Blog
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my simple photoblog where I post a weekly photo (usually of my family).  In each post I'll tell a short story about the photograph along with some technical details.  The purpose of this site is to document my family's life while hopefully improving my photography in the process.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://photoblog.jonwhite.me" # the base hostname & protocol for your site
twitter_username: jjwhite
instagram_username: jjwhite

# Build settings
markdown: kramdown
